export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const VIDEO_REQUEST = 'VIDEO_REQUEST';
export const VIDEO_SUCCESS = 'VIDEO_SUCCESS';
export const VIDEO_FAILURE = 'VIDEO_FAILURE';

export const VIDEOS_REQUEST = 'VIDEOS_REQUEST';
export const VIDEOS_SUCCESS = 'VIDEOS_SUCCESS';
export const VIDEOS_FAILURE = 'VIDEOS_FAILURE';

export const VIDEO_RATING_REQUEST = 'VIDEO_RATING_REQUEST';
export const VIDEO_RATING_SUCCESS= 'VIDEO_RATING_SUCCESS';
export const VIDEO_RATING_FAILURE = 'VIDEO_RATING_FAILURE';

